# Project information
site_name: Women in Data Science
site_url: https://widsireland.github.io/WiDSIrelandLab2025/
site_author: IBM Research
site_description: Women in Data Science Page.

# Repository
repo_name: WiDSIreland/WiDSIrelandLab2025
repo_url: https://github.com/WiDSIreland/WiDSIrelandLab2025
# Source Docs & Site Docs
docs_dir: "docs"
site_dir: "site"

# Navigation
nav:
  - Welcome:
      - About the workshop: README.md
  - Workshop:
      - Lab 0. Pre-work: pre-work/readme.md
      - Lab 1. Summarize a text document with Granite: lab-1/readme.md
      - Lab 2. Retrieval Augmented Generation (RAG) with Langchain: lab-2/readme.md
      - Lab 3. Energy Demand Forecasting with Granite Timeseries (TTM): lab-3/readme.md
  - References:
      - IBM Granite Community: https://github.com/ibm-granite-community

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2024- IBM Research


