# Project information
site_name: Women in Data Science
site_url: https://widsireland.github.io/WiDSIrelandLab2025/
site_author: IBM Research
site_description: Women in Data Science Page.

# Repository
repo_name: WiDSIreland/WiDSIrelandLab2025
repo_url: https://github.com/WiDSIreland/WiDSIrelandLab2025
# Source Docs & Site Docs
docs_dir: "docs"
site_dir: "site"

# Navigation
nav:
  - Welcome:
      - About the workshop: index.md
  - Workshop:
      - Lab 0. Pre-work: pre-work/readme.md
      - Lab 1. Summarize a text document with Granite: lab-1/readme.md
      - Lab 2. Retrieval Augmented Generation (RAG) with Langchain: lab-2/readme.md
      - Lab 3. Energy Demand Forecasting with Granite Timeseries (TTM): lab-3/readme.md
  - References:
      - IBM Granite Community: https://github.com/ibm-granite-community

## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2024- IBM Research

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

# Theme
theme:
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - content.code.copy
    - navigation.tabs
  name: material
  palette:
    # Palette toggle for light mode

    - scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode

    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
